### ISSUE TITLE
Touchscreen to button input : Left is defined twice

### ISSUE THREAD

**Issue by Tijgerd** [adafruit/Adafruit_Arcada#10]
Touchscreen "Left" readout is done twice:

https://github.com/adafruit/Adafruit_Arcada/blob/c75927414bbded71239a0da4840ff560fb74f185/Adafruit_Arcada.cpp#L416-L419

and

https://github.com/adafruit/Adafruit_Arcada/blob/c75927414bbded71239a0da4840ff560fb74f185/Adafruit_Arcada.cpp#L425-L428

**Comment by Tijgerd** [comment]
Wanted to make a new PR but accidentally I pushed this to PR: https://github.com/adafruit/Adafruit_Arcada/pull/8

**Comment by ladyada** [comment]
ooh want to try a new branch-PR?

**Comment by Tijgerd** [comment]
Since it just is the removal of 4 lines of code (which are already present 4 lines earlier),
I think it can be in the same PR as https://github.com/adafruit/Adafruit_Arcada/pull/8
