### ISSUE TITLE
Trouble with compiling for pybadge

### ISSUE THREAD

**Issue by chrisleewoo** [adafruit/Adafruit_Arcada#11]
Arduino: 1.8.9 (Windows 10), Board: "Adafruit pyBadge M4 Express (SAMD51), Enabled, 120 MHz (standard), Small (-Os) (standard), 24 MHz (standard), 50 MHz (standard)"

In file included from D:\Code\Arduino\libraries\Adafruit_Arcada/Adafruit_Arcada.h:9:0,

                 from D:\Code\Arduino\Pybadge_Arcada\Pybadge_Arcada.ino:1:

D:\Code\Arduino\libraries\Adafruit_GFX_Library/Adafruit_SPITFT.h:90:61: note: #pragma message: GFX DMA IS ENABLED. HIGHLY EXPERIMENTAL.

  #pragma message ("GFX DMA IS ENABLED. HIGHLY EXPERIMENTAL.")

                                                             ^

In file included from D:\Code\Arduino\libraries\Adafruit_QSPI/Adafruit_QSPI_GD25Q.h:11:0,

                 from D:\Code\Arduino\libraries\Adafruit_Arcada/Adafruit_Arcada.h:154,

                 from D:\Code\Arduino\Pybadge_Arcada\Pybadge_Arcada.ino:1:

D:\Code\Arduino\libraries\Adafruit_QSPI/Adafruit_QSPI_Generic.h:28:20: error: 'spiflash_type_t' has not been declared

  bool setFlashType(spiflash_type_t t);

                    ^

In file included from D:\Code\Arduino\Pybadge_Arcada\Pybadge_Arcada.ino:1:0:

D:\Code\Arduino\libraries\Adafruit_Arcada/Adafruit_Arcada.h:157:11: error: 'Adafruit_SPIFlash_FAT' does not name a type

   typedef Adafruit_SPIFlash_FAT::File File;

           ^

exit status 1
Error compiling for board Adafruit pyBadge M4 Express (SAMD51).

**Comment by ladyada** [comment]
please make sure you have the super latest libraries of everything - a lot got updated recently :)
