### ISSUE TITLE
play_fs_wav.h (?)

### ISSUE THREAD

**Issue by grajohnt** [adafruit/Adafruit_Arcada#16]
In the arcada_audio_waveplayer.ino sketch, 'play_fs_wav.h' is referenced.

I can't find any other references for this anywhere - where should it come from?

**Comment by ladyada** [comment]
hiya its in Audio :) its only for use with samd51 chips\
https://github.com/adafruit/Audio

**Comment by grajohnt** [comment]
Argh - picked up the Arduino Audio lib instead! Terribly sorry!

**Comment by ladyada** [comment]
all good :)
