### ISSUE TITLE
void Adafruit_Arcada_SPITFT::alertBox adds a space after a \n (fix suggested)

### ISSUE THREAD

**Issue by tsupplis** [adafruit/Adafruit_Arcada#25]
- Arduino board:  Edge Badge

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.10

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): 

Code:
```
  sprintf(message, "Yes, you selected '%s'.\nWell done!", "Apples'");
  arcada.infoBox(message,2);
```
Will display:

```
Yes, you selected 
'Apples'.
 Well done!"
```
(notice the space before Well done.

A fix is in Adafruit_Arcada_Alerts::alertBox on line 137

```
(old)<      fontX += charWidth;
(new)>      if (string[c] != '\n') fontX += charWidth;
```

**Comment by ladyada** [comment]
thanks, can you submit a PR? it would be appreicated :)

**Comment by tsupplis** [comment]
Done 😉.
https://github.com/adafruit/Adafruit_Arcada/pull/26

**Comment by ladyada** [comment]
ok! :D
