### ISSUE TITLE
Timers not firing on pygamer

### ISSUE THREAD

**Issue by Chrs2021** [adafruit/Adafruit_Arcada#34]
I am using a pygamer and the latest libraries. 

Beyond my own project the timercallback function isn't working in the arcada pygamer test sketch either (not firing).
I don't have another compatible board to test with but looking at source it looks like these timers are backed by adafruit_zerotimers which by the looks of it is experimental code that isn't guaranteed to work. 

Is this expected behavior?

**Comment by ladyada** [comment]
just tested arcada_callback with a pybadge and it works fine. please try the example

**Comment by ladyada** [comment]
closed for lack of response
